### ISSUE TITLE
 from langgraph.store.memory import InMemoryStore ImportError: cannot import name 'InMemoryStore' from 'langgraph.store.memory' 

### ISSUE THREAD

**Issue by Halil3509** [langchain-ai/memory-agent#2]
I got this error because there is no folder called the store in Langgraph's latest version. 

![image](https://github.com/user-attachments/assets/fb8dd5ca-f236-43ad-a5bc-3877311f9a7e)

How do you think I could solve this problem? 

![image](https://github.com/user-attachments/assets/b5248aae-1a66-4b6a-b890-b0cc8a88a55c)

**Comment by Olim4ik** [comment]
Hey! This way works work me:

from langchain.storage.in_memory import InMemoryStore

langgraph version = 0.2.23

**Comment by hinthornw** [comment]
Different than langchain.storage.inmemory

The resolution is to upgrade langgraph-checkpoint vresion
