### ISSUE TITLE
Alternative to InMemoryStore

### ISSUE THREAD

**Issue by gyi123** [langchain-ai/memory-agent#4]
Great intorduction!
Any example how to use production-level BaseStotre other than InMemoryStore? Such as Postgres, Redis or Firestore?

**Comment by hinthornw** [comment]
https://langchain-ai.github.io/langgraph/reference/store/#langgraph.store.postgres.PostgresStore

**Comment by gyi123** [comment]
> https://langchain-ai.github.io/langgraph/reference/store/#langgraph.store.postgres.PostgresStore

Work like a Charm. Thank you!

**Comment by ZhihaoZhang97** [comment]
Hi @hinthornw thank you for pointing out the document. I am pretty new to the langgraph platfrom. 

Would you mind explaining a bit more about how to set-up the connection pool for the graph if I wish to push the code to the langgraph studio for production? 

If my understanding is correct, the `await store.setup()` should only run once during deployment:
```
async with AsyncPostgresStore.from_conn_string(conn_string) as store:
    await store.setup()  # Run migrations. Done once

    # Store and retrieve data
    await store.aput(("users", "123"), "prefs", {"theme": "dark"})
    item = await store.aget(("users", "123"), "prefs")
``` 
But if I put this code in the `tool.py` script, it would run migrations everytime when the tool is called, which is not a good practice. I am not sure what would be a good entry point when deploying to langgraph studio (such as a seperate `setup_db.py` file, maybe?), so I could run a script once at the beginning of the deployment to setup the database and then just insert the long-term memory data into the database.

I am thinking about the `langgraph.json`, is that possible to put any settings in there? or if there is any other way to solve this?

Thank you for any help in advance!
